import { precacheAndRoute } from 'workbox-precaching'

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Listen for push events
self.addEventListener('push', function(event) {
  const data = event.data ? event.data.text() : 'Default Push Notification'
  
  const options = {
    body: data,
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png'
  }

  event.waitUntil(
    self.registration.showNotification('Urban Harvest Hub', options)
  )
})

// Listen for notification click
self.addEventListener('notificationclick', function(event) {
  event.notification.close()
  event.waitUntil(
    clients.openWindow('/')
  )
})
