import { precacheAndRoute } from 'workbox-precaching'

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Listen for push events
self.addEventListener('push', function(event) {
  let title = 'Urban Harvest Hub';
  let body = 'Default Push Notification';

  if (event.data) {
    try {
      const data = event.data.json();
      title = data.title || title;
      body = data.body || body;
    } catch (e) {
      body = event.data.text();
    }
  }

  const options = {
    body: body,
    icon: '/pwa-192x192.png',
    badge: '/favicon.svg'
  }

  event.waitUntil(
    self.registration.showNotification(title, options)
  )
})

// Listen for notification click
self.addEventListener('notificationclick', function(event) {
  event.notification.close()
  event.waitUntil(
    clients.openWindow('/')
  )
})
