import { precacheAndRoute } from 'workbox-precaching'

// Precache the assets generated by Vite
const manifest = self.__WB_MANIFEST;
if (manifest) {
  precacheAndRoute(manifest);
}

// Listen for activation
self.addEventListener('activate', (event) => {
  console.log('Service Worker activated');
  event.waitUntil(self.clients.claim());
});

// Listen for push events
self.addEventListener('push', (event) => {
  console.log('🔔 push event received', event);
  let title = 'Urban Harvest Hub';
  let body = 'Default Push Notification';

  if (event.data) {
    try {
      const data = event.data.json();
      title = data.title || title;
      body = data.body || body;
    } catch (e) {
      body = event.data.text();
    }
  }

  const options = {
    body,
    icon: '/pwa-192x192.png',
    badge: '/favicon.svg'
  };

  event.waitUntil(self.registration.showNotification(title, options).then(() => {
    console.log('🔔 notification shown', title, options);
  }));
});

// Listen for notification click
self.addEventListener('notificationclick', function(event) {
  event.notification.close()
  event.waitUntil(
    clients.openWindow('/')
  )
});

// Runtime Caching for API routes (Network First falling back to Cache)
self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Only handle GET requests for our API endpoints (products, workshops, events, stats)
  if (
    request.method === 'GET' &&
    (url.pathname.includes('/products') ||
     url.pathname.includes('/workshops') ||
     url.pathname.includes('/events') ||
     url.pathname.includes('/stats'))
  ) {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.status === 200) {
            const cacheCopy = response.clone();
            caches.open('api-cache').then((cache) => {
              cache.put(request, cacheCopy);
            });
          }
          return response;
        })
        .catch(() => {
          return caches.match(request);
        })
    );
  }
});
